# This file was generated by GoReleaser. DO NOT EDIT.
class Foreplay < Formula
  desc "Software to manage Git pre-commit hooks."
  homepage "https://github.com/eberkund/foreplay"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/eberkund/foreplay/releases/download/v0.1.0/foreplay_0.1.0_darwin_amd64.zip"
    sha256 "f59a3a322c8f5bb5a03bb691bcfbb87946445f47a981cd6def102f4dd7361fad"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/eberkund/foreplay/releases/download/v0.1.0/foreplay_0.1.0_linux_amd64.zip"
      sha256 "f3914aaf6f399baa0067c51e14ea6b11cbde4a898c18a3d4276861c0dab7b98a"
    end
  end

  def install
    bin.install "foreplay"
  end

  test do
    system "#{bin}/foreplay help"
  end
end
