# This file was generated by GoReleaser. DO NOT EDIT.
class Foreplay < Formula
  desc "Software to manage Git pre-commit hooks."
  homepage "https://github.com/eberkund/foreplay"
  version "0.4.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/eberkund/foreplay/releases/download/v0.4.0/foreplay_0.4.0_darwin_amd64.zip"
    sha256 "2ffa897ea86dc5dc2905526bc7283aa70f41bbf8f59dcb2abc52c51656485753"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/eberkund/foreplay/releases/download/v0.4.0/foreplay_0.4.0_linux_amd64.zip"
      sha256 "365bab4d2b7ec2ac04946370b4c9249942818b7b3e96f2907d1cd5bec6047552"
    end
  end

  def install
    bin.install "foreplay"
  end

  test do
    system "#{bin}/foreplay help"
  end
end
